CLASSES:
    - fake
    - junk
    - photocopy
    - real
INPUT:
    SIZE: 1024        
MODEL:
    PIXEL_MEAN:
        - 0.485
        - 0.456
        - 0.406
    PIXEL_STD:
        - 0.229
        - 0.224
        - 0.225
    NUM_CLASSES: 4
    WEIGHTS: /data/quocpbc/notebooks/nic/doc/classification.pth
